name: Test
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      run: rustup toolchain add ${{ matrix.rust }}
    - name: Check formatting
      run: cargo fmt --check --verbose
    - name: Run tests
      run: cargo test --verbose
